# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: job_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'job_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11job_service.proto\x12\njobservice\"\x07\n\x05\x45mpty\"\x1c\n\nJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\",\n\x06NewJob\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"=\n\x0bJobResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"0\n\x07JobList\x12%\n\x04jobs\x18\x01 \x03(\x0b\x32\x17.jobservice.JobResponse2\xb4\x01\n\nJobService\x12\x31\n\x07GetJobs\x12\x11.jobservice.Empty\x1a\x13.jobservice.JobList\x12\x39\n\x06GetJob\x12\x16.jobservice.JobRequest\x1a\x17.jobservice.JobResponse\x12\x38\n\tCreateJob\x12\x12.jobservice.NewJob\x1a\x17.jobservice.JobResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=33
  _globals['_EMPTY']._serialized_end=40
  _globals['_JOBREQUEST']._serialized_start=42
  _globals['_JOBREQUEST']._serialized_end=70
  _globals['_NEWJOB']._serialized_start=72
  _globals['_NEWJOB']._serialized_end=116
  _globals['_JOBRESPONSE']._serialized_start=118
  _globals['_JOBRESPONSE']._serialized_end=179
  _globals['_JOBLIST']._serialized_start=181
  _globals['_JOBLIST']._serialized_end=229
  _globals['_JOBSERVICE']._serialized_start=232
  _globals['_JOBSERVICE']._serialized_end=412
# @@protoc_insertion_point(module_scope)
